Fixup `CorrelatedStack` slicing behavior
lumicks/pylake pull request #249
Opened 2022-01-07 14:29 UTC by rpauszek

**Why this PR?**
I noticed some weird behavior when attempting to slice a stack in reverse (`stack[5:2]`) which ended up giving a new instance with `stack.num_frames < 0`, which obviously doesn't make sense. Since there is no "empty set" version for `CorrelatedStack` as would be the default behavior for this slicing in python, we decided to just throw. Additionally, we now throw when the resulting slice is empty (`stack[5:5]`).

I also took this opportunity to split up the tests a bit, in line with the recent overhaul #241. The last 2 commits are just moving the original test file, and then copy/paste some tests into new files for manageability.

2022-01-10 10:37 UTC, tiagobonetti reviewed
Looks good to me. 

I'm not sure this is a breaking change since it only breaks things that make no sense anyway, but we probably need some notes about it for the changelog.

2022-01-10 13:35 UTC, rpauszek commented on lumicks/pylake/tests/test_correlated_stack.py
> +        assert(stack[2:5][3:5].num_frames == 0)
Good point, my initial instinct was not to delete any tests. Instead, I added another specific test for iterative slicing

2022-01-11 09:42 UTC, JoepVanlier requested changes
I didn't review this one in detail, but just two minor things I noticed.

I like that you added tests for the slicing that actually test the data.

2022-01-11 09:42 UTC, JoepVanlier commented on lumicks/pylake/tests/test_imaging_camera/test_correlated_stack.py
> +
I like that we now have all these slicing tests.

I'd suggest three extra cases:
```python
    compare_frames([1, 2, 3, 4, 5, 6, 7, 8, 9], stack0[1:1000])  # test clamping past the end
    compare_frames([0, 1, 2, 3, 4, 5, 6, 7, 8], stack0[-1000:10])  # test clamping past the beginning
    compare_frames([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], stack0[-1000:1000])  # test clamping both dirs
```

2022-01-11 09:48 UTC, JoepVanlier commented on lumicks/pylake/tests/test_imaging_camera/test_correlated_stack.py
> +    compare_frames([3, 4], stack0[2:6][1:3]) #  iterative slicing
Would be nice to stick to PEP8 commenting style like the first 5.

2022-01-11 12:01 UTC, JoepVanlier approved these changes
LGTM!

2022-01-11 14:07 UTC, merged