Get rid of CalibratedKymographChannel
lumicks/pylake pull request #298
Opened 2022-04-22 13:23 UTC by rpauszek

**Why this PR?**

Previously we needed an intermediate utility class between `Kymo` and the kymotracking algorithms (specifically to handle downsampled kymos). However, with the current structure this class has become just an extra layer with no real purpose. So let's get rid of it.

**What to look for:**
- I started by going through each module that depended on `CalibratedKymographChannel` and removed all dependencies
- Added some convenience features to `KymoLine` in order to simplify some code; I kept them public as it seems `line_time_seconds` and `pixelsize` are useful features
- `CalibratedKymographChannel._to_pixel_rect()` was only used to set the ROI in the kymotracker widget, so I made this a standalone function there; in the future we may want to think about having a dedicated ROI class for this kind of stuff (along with widefield)
- None of the assertions were touched in the tests; the only changes are creating the test data, primarily switching from `CalibratedKymographChannel` to `Kymo`
- Removed the pixel/physical conversion methods (ie, `from_position`, `to_seconds`, etc...) as these are one-liners and only used in one or two places
- Changed the calculation of the `extent` argument for `Kymo` plotting. Now it is the same as what `CalibratedKymographChannel` had and defines the pixel position at the center (same as we do with the time axis)

2022-05-03 15:32 UTC, JoepVanlier requested changes
Great work! It's great that we've gotten rid of that wart.

One thing to think about for a future PR would be to have a more central place for these coordinate transforms. I'm a little concerned about having many places with these same linear transforms (between (rounded) pixels and coordinates/seconds). Without a way to easily convert between them in a central location it seems likely that we end up spreading transformations around.

Please don't forget to add a changelog entry!

2022-05-04 13:35 UTC, rpauszek commented on lumicks/pylake/nb_widgets/kymotracker_widgets.py
> +        _data = kymo.get_image(channel)
temporary insanity?

2022-05-04 13:36 UTC, rpauszek commented on lumicks/pylake/kymotracker/kymoline.py
> +    def line_time_seconds(self):
sure sounds good. I just made them both private, we can always change it later

2022-05-05 08:14 UTC, JoepVanlier commented on lumicks/pylake/nb_widgets/kymotracker_widgets.py
> +        _data = kymo.get_image(channel)
😆

2022-05-05 08:19 UTC, JoepVanlier commented on lumicks/pylake/kymotracker/kymotracker.py
> +        for (seconds, position) in rect
Decided to keep it as it is.

2022-05-05 08:28 UTC, JoepVanlier approved these changes
:shipit:

2022-05-05 08:28 UTC, JoepVanlier commented on lumicks/pylake/kymotracker/tests/test_kymoline.py
> +    assert k1._kymo == blank_kymo
👍

2022-05-05 09:09 UTC, merged