Create kymographs from image arrays
lumicks/pylake pull request #326
Opened 2022-06-29 13:46 UTC by rpauszek

**Why this PR?**
Creating kymos from image data opens up multiple possibilities including creating kymographs from `CorrelatedStack`s and exploring kymotracking on new types of image transformations (eg., edge detection).  Per-pixel timestamps are not supported, but the line time (frame integration time in the case of camera-based images) must be supplied. This way, these kymos can be used in most downstream analysis including kymotracking

2022-06-29 16:10 UTC, JoepVanlier requested changes
Great work. Code-wise it looks nice, but I have a few requests and questions.

2022-06-30 07:43 UTC, JoepVanlier reviewed
Sorry for piggybacking more comments/requests on this, but I had another look this morning.

There are several members that don't give outputs that users can't do anything with.

`blue_power`, `red_power`, `green_power`, `green_photon_count`, `blue_photon_count`, `red_photon_count`, `infowave`, `sted_power` all give:
`AttributeError: 'NoneType' object has no attribute 'green_photon_count'`

The function `plot_with_force` also doesn't work.

This makes sense, since most of these fail because of the absence of `Kymo.file`, but it'd be good to have a better error message. I think many of these could be caught by making `file` a property with a fail path that has a sensible error message.

This error message is not particularly helpful.

When I use crop_and_calibrate, I get `NotImplementedError: Slicing is not implemented for processed kymographs. Please slice prior to processing the data.`. It would be nice to generalize this error message a bit, since this is not the reason it fails in this case.

2022-07-01 12:16 UTC, rpauszek commented on lumicks/pylake/kymo.py
> +    )
good catch, I think it was leftover from when I rebased on top of the position calibration fix

2022-07-04 08:43 UTC, rpauszek commented on lumicks/pylake/tests/test_imaging_confocal/test_kymo_from_array.py
> +        arr_kymo.pixel_time_seconds
Yup forgot about that one. Added a warning and just store `None` for the pixel time in the exported metadata

2022-07-04 08:44 UTC, rpauszek commented
all good points, there's so much functionality to cover but I think now everything is handled and tested

2022-07-06 15:32 UTC, JoepVanlier commented on lumicks/pylake/tests/test_imaging_confocal/test_kymo_from_array.py
> +        arr_kymo.pixel_time_seconds
Unfortunately, `save_tiff` does not handle it gracefully if `pixel_size_um` is `None` (since it'll try and divide it by a float).

2022-07-06 16:17 UTC, merged