channel: fixed `TimeSeries.from_dataset()` not lazy loading data
lumicks/pylake pull request #366
Opened 2022-08-29 18:11 UTC by tobiasjj

The method `TimeSeries.from_dataset()` automatically loaded the data and timestamps from an HDF5 file upon creation of a `TimeSeries` instance. This is now avoided by creating the `TimeSeries` instance using the `h5py.Dataset.fields()` method of data and timestamps.

2022-08-30 09:00 UTC, ab412 commented on changelog.md
> +* Fix method `TimeSeries.from_dataset()` reading all data from datasets upon creation of a `TimeSeries` instance instead of lazy loading
*Fixed

2022-08-31 07:52 UTC, ab412 approved these changes
The `pytest`  on my machine said it is working 🙂  Go for launch 🚀

2022-08-31 10:12 UTC, JoepVanlier requested changes
If I try to create one of these, it fails when it tries to assert `len(data) == len(timestamps)` in the constructor with `TypeError: object of type 'FieldsWrapper' has no len()`.

Seems that this length property being defined depends on a newer version of `h5py` than we require. See: https://docs.h5py.org/en/stable/whatsnew/3.4.html

2022-08-31 12:20 UTC, tobiasjj commented
I bumped the required h5py version to `>=3.4, <4` and also changed the `TimeSeries.__len__()` method to use the uncached source data instead of using the cached `data` property.

2022-08-31 16:13 UTC, JoepVanlier approved these changes
Old:
```python
143.9609375
f = file.downsampled_force1x
146.203125
f.data
146.203125
```
New:
```python
143.6953125
f = file.downsampled_force1x
144.4921875
f.data
146.12109375
```

Works as advertised! :shipit:

2022-08-31 19:48 UTC, merged