Line to track the finale
lumicks/pylake pull request #368
Opened 2022-08-30 13:13 UTC by rpauszek

**Why this PR?**

This is the final PR to align the "line" vs "track" terminology, focused on the kymotracker widget

Docs build [here](https://lumicks-pylake.readthedocs.io/en/line_to_track_the_finale/examples/cas9_kymotracking/cas9_kymotracking.html)

2022-08-31 10:36 UTC, JoepVanlier requested changes
Couldn't find anything controversial in this one. Only request is to fix a small duplicate line :)

2022-08-31 10:36 UTC, JoepVanlier commented on lumicks/pylake/nb_widgets/kymotracker_widgets.py
> +        action="always",
👍

2022-08-31 10:36 UTC, JoepVanlier commented on changelog.md
> +* The `KymoWidgetGreedy` attributes/function `plotted_lines`, `show_lines`, `adding` and `update_lines()` have been removed (replaced with private API).
👍

2022-08-31 10:36 UTC, JoepVanlier commented on lumicks/pylake/nb_widgets/kymotracker_widgets.py
> +    )
Parameters will through a warning on the docs build :(

2022-08-31 10:36 UTC, JoepVanlier commented on lumicks/pylake/nb_widgets/kymotracker_widgets.py
> +        self.tracks.save(filename, delimiter, sampling_width)
Rebase mishap?

2022-08-31 10:36 UTC, JoepVanlier commented on docs/examples/cas9_kymotracking/cas9_kymotracking.rst
> +        cmap="viridis"
:)

2022-08-31 15:02 UTC, rpauszek commented on lumicks/pylake/nb_widgets/kymotracker_widgets.py
> +        self.tracks.save(filename, delimiter, sampling_width)
😒

2022-09-01 12:40 UTC, JoepVanlier approved these changes
Looks good to me.

2022-09-02 09:03 UTC, merged