Add custom mapping of photon counter channels to RGB colors
lumicks/pylake pull request #570
Opened 2023-09-15 13:39 UTC by agom

This allows reconstruction of images from systems where the photon detector channels are not named with the standard "Red, "Green", and "Blue" names.

For example, this image is reconstructed from a file where the photon count channels are named `Detector 1`, `Detector 2`, `Detector 3` and `Detector 4`. 

![output](https://github.com/lumicks/pylake/assets/17353250/20b2b47c-f578-45d5-8d65-d77f625d11a7)

Draft because needs additional tests.

2023-09-25 10:01 UTC, JoepVanlier requested changes
I know it's still a draft, but I commented a few things I noticed.

I don't see the added value of using the enumerator `class` here. For public API, I feel this would only add unnecessary friction. Internally, we could use it, but then it would involve conversions on API endpoints such as `get_image`, and I'm not sure if it would add enough for that to be worth it?

I cannot comment on those particular lines, but note that `File.from_h5py` bypasses `__init__` and therefore needs a valid `rgb_to_detectors` to be defined.

I would also prefer to have some input validation when users provide these custom channels. Checking whether those datasets exist (if specified) and failing early seems better and more helpful than just silently returning empty channels and blank images later.

2023-09-25 15:53 UTC, agom commented
> I know it's still a draft, but I commented a few things I noticed.
> 
> I don't see the added value of using the enumerator `class` here. For public API, I feel this would only add unnecessary friction. Internally, we could use explicit enumeration, but then it would involve conversions on API endpoints such as `get_image`, and I'm not sure if it would add enough for that to be worth it? To me, it seems like just using a `str` -> `str` mapping is simpler.
> 
> I cannot comment on those particular lines, but note that `File.from_h5py` bypasses `__init__` and therefore needs a valid `rgb_to_detectors` to be defined.
> 
> I would also prefer to have some input validation when users provide these custom channels. Checking whether those datasets exist (if specified) and failing early seems better and more helpful than just silently returning empty channels and blank images later.

Thanks for the review! I was already on the fence with the `enum` so I'll just remove it, hopefully, I can come back to this in next few days.

2024-01-23 13:12 UTC, JoepVanlier approved these changes
Looks good! A few minor suggestions, but other than that :shipit:

2024-01-23 13:12 UTC, JoepVanlier commented on lumicks/pylake/tests/test_file/test_file.py
> +    )
```suggestion
    )
    assert np.any(f.red_photon_count.data)
```
Maybe verify that we actually have the data present (I could still remove the mapping entirely without triggering an error).

2024-01-23 16:35 UTC, merged