More options of image plotting `channel` argument
lumicks/pylake pull request #571
Opened 2023-09-19 13:39 UTC by rpauszek

**Why this PR?**
Enable some extra conveniences:
- alias single-channel plotting (eg, `kymo.plot("r")` instead of `kymo.plot("red")`
- enable 2-channel plotting (eg, `kymo.plot("rg")` and ignore the blue channel)

*note: I had to change the error message thrown if an invalid channel argument is supplied to `export_video`. There was no way to get around this as we hard-coded in the previous choices. However the type `ValueError` remains the same

2023-09-25 15:32 UTC, JoepVanlier requested changes
Wonderful feature.

I noticed a small breaking change and added a few other suggestions. Nothing major. Very nice code.

2023-09-25 15:32 UTC, JoepVanlier commented on lumicks/pylake/scan.py
>                  raise RuntimeError("Invalid channel selected")
👍

2023-09-26 12:02 UTC, rpauszek commented on lumicks/pylake/detail/plotting.py
> +        raise ValueError(f"color channel must be in 'rgb' order, got '{channel}'.")
so many walrusesses 😁

2023-09-26 12:03 UTC, rpauszek commented on lumicks/pylake/detail/widefield.py
> -        if channel.lower() == "rgb":
I actually just missed that I had gotten rid of the case checking, good catch

2023-09-26 12:05 UTC, JoepVanlier approved these changes
Excellent!

2023-09-26 14:59 UTC, merged