Rework confocal downsampling tests
lumicks/pylake pull request #573
Opened 2023-09-22 12:51 UTC by rpauszek

Why this PR?
Continuing from #572, here I've tackled all of the tests dealing with kymo downsampling. Same strategy as before

2023-09-25 17:03 UTC, JoepVanlier requested changes
Good stuff! Most of it looks good, but I did leave a few comments.

One thing that I am wondering about is the `kymo_h5_file` which is now different. It is involved in more tests than the ones moved here, so I'm curious.

2023-09-27 13:26 UTC, rpauszek commented on lumicks/pylake/tests/test_imaging_confocal/conftest.py
> +    force_data[260:] = 10
In the old fixture we use the same kymo as our typical test one ("Kymo1") which is analogous to what I do here. Just using sane values for the timestamps, as I've been introducing throughout.

I noticed the regression test too, but my original thought was to have a separate fixture for that so we don't get anything funky interfering with other tests. So basically we'd have a "good" fixture and a "weird" fixture. Looking now more closely at that test, we actually introduce the "weirdness" in the test itself (monkeypatch in a smaller stop time), so the changes made here should still work fine for that one. 

That being said, I agree it'd be nice to have some very different values in the deadtime so we'd easily spot off-by-one errors, so I'll add that part

2023-10-06 14:14 UTC, JoepVanlier commented on lumicks/pylake/tests/test_imaging_confocal/conftest.py
> +def downsampled_results():
Fair enough!

2023-10-06 14:21 UTC, JoepVanlier commented on lumicks/pylake/tests/test_imaging_confocal/conftest.py
> +    force_data[260:] = 10
Alright. Sounds reasonable to me!

2023-10-06 14:21 UTC, JoepVanlier approved these changes
:shipit:

2023-10-27 11:30 UTC, merged