examples: determine effective kon
lumicks/pylake pull request #713
Opened 2024-12-11 10:18 UTC by aafkevandenberg

I added an example for a frequently requested workflow: kon.
In this draft pull request, I'd like feedback on the overall workflow and the methods used. 

Docs can be found here: https://lumicks-pylake.readthedocs.io/en/example_kon/examples/kon/kon.html

2024-12-19 14:00 UTC, JoepVanlier requested changes
Great work!

I mostly commented some minor things, but I have one potential issue that you should probably consider regarding the track order and/or overlaps.

2025-01-06 14:55 UTC, aafkevandenberg commented on docs/examples/kon/kon.rst
> +The protein binds and unbinds to target sites on DNA and the result is recorded as a kymograph.
Good point. I'll add a note that this tutorial assumes that bleaching time >> binding time. This is what we advise for these type of experiments. 

And correction to your note: t_on  _shortens__, while t_off _lengthens_ due to photobleaching

Looking at the paper, t_on, corresponds to the binding lifetime (so 1/koff), in our experiments. Equation 17 is a common approach to include the bleaching time (some authors used it, including me) and I was about to incorporate it in a tutorial. 

It would be great to include the bleaching time as an optional parameter in the Pylake functions for fitting exponential distributions. Often, users don't know the bleaching time, as a permanently bound dye is required to measure this quantity, but it can eg be measured on a dye stuck to the surface.

I have never seen the approach to determine t_off while accounting for bleaching, but it makes sense that the off time lengthens when including bleaching.

2025-01-06 17:05 UTC, JoepVanlier commented on docs/examples/kon/kon.rst
> +The protein binds and unbinds to target sites on DNA and the result is recorded as a kymograph.
Sorry, I meant tau, but you're right of course. For now, I think adding that note and mentioning that bleaching isn't taken into account is sufficient.

And nice! Makes sense! Looking forward to that tutorial.

2025-03-06 09:29 UTC, aafkevandenberg commented on docs/examples/kon/kon.rst
> +        intervals =  [tracks[x+1].seconds[0]-tracks[x].seconds[-1] for x in range(len(tracks)-1)]
I included a function that checks for overlap and throws an error if overlap between events is detected on this single kymograph. 
The user then would have to make sure that the group is from a single kymograph.

2025-03-06 10:01 UTC, JoepVanlier approved these changes
Looks great!

2025-03-06 10:09 UTC, merged